package com.lmsapp.pojo;
// Generated 10-Jan-2024, 10:26:20 am by Hibernate Tools 6.3.1.Final

import java.sql.Timestamp;

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

	private int adminid;
	private User user;
	private String name;
	private String description;
	private Timestamp createddate;
	private Timestamp updateddate;

	public Admin() {
	}

	public Admin(int adminid, User user, String name, String description, Timestamp createddate,
			Timestamp updateddate) {
		this.adminid = adminid;
		this.user = user;
		this.name = name;
		this.description = description;
		this.createddate = createddate;
		this.updateddate = updateddate;
	}

	public int getAdminid() {
		return this.adminid;
	}

	public void setAdminid(int adminid) {
		this.adminid = adminid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Timestamp getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Timestamp createddate) {
		this.createddate = createddate;
	}

	public Timestamp getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Timestamp updateddate) {
		this.updateddate = updateddate;
	}

}
