package com.lmsapp.pojo;
// Generated 10-Jan-2024, 10:26:20 am by Hibernate Tools 6.3.1.Final

import java.sql.Timestamp;

/**
 * Systemadmin generated by hbm2java
 */
public class Systemadmin implements java.io.Serializable {

	private int sysid;
	private User user;
	private Timestamp createddate;
	private Timestamp updateddate;

	public Systemadmin() {
	}

	public Systemadmin(int sysid, User user, Timestamp createddate, Timestamp updateddate) {
		this.sysid = sysid;
		this.user = user;
		this.createddate = createddate;
		this.updateddate = updateddate;
	}

	public int getSysid() {
		return this.sysid;
	}

	public void setSysid(int sysid) {
		this.sysid = sysid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Timestamp getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Timestamp createddate) {
		this.createddate = createddate;
	}

	public Timestamp getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Timestamp updateddate) {
		this.updateddate = updateddate;
	}

}
