package com.lmsapp.pojo;
// Generated 10-Jan-2024, 10:26:20 am by Hibernate Tools 6.3.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int userid;
	private String emailid;
	private String phone;
	private String password;
	private boolean status;
	private String usertype;
	private Timestamp createddate;
	private Timestamp updateddate;
	private Set admins = new HashSet(0);
	private Set systemadmins = new HashSet(0);

	public User() {
	}

	public User(int userid, String emailid, String phone, String password, boolean status, String usertype,
			Timestamp createddate, Timestamp updateddate, Set admins, Set systemadmins) {
		this.userid = userid;
		this.emailid = emailid;
		this.phone = phone;
		this.password = password;
		this.status = status;
		this.usertype = usertype;
		this.createddate = createddate;
		this.updateddate = updateddate;
		this.admins = admins;
		this.systemadmins = systemadmins;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public String getEmailid() {
		return this.emailid;
	}

	public void setEmailid(String emailid) {
		this.emailid = emailid;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	public String getUsertype() {
		return this.usertype;
	}

	public void setUsertype(String usertype) {
		this.usertype = usertype;
	}

	public Timestamp getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Timestamp createddate) {
		this.createddate = createddate;
	}

	public Timestamp getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Timestamp updateddate) {
		this.updateddate = updateddate;
	}

	public Set getAdmins() {
		return this.admins;
	}

	public void setAdmins(Set admins) {
		this.admins = admins;
	}

	public Set getSystemadmins() {
		return this.systemadmins;
	}

	public void setSystemadmins(Set systemadmins) {
		this.systemadmins = systemadmins;
	}

}
